default_language_version:
    python: python3.7

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 0408045bd1118e706f789f2611b04f211d962bb7
    hooks:
    -   id: trailing-whitespace
        language_version: python3
    -   id: end-of-file-fixer
        language_version: python3
    -   id: check-yaml
        language_version: python3
    -   id: debug-statements
        language_version: python3
-   repo: https://github.com/ambv/black
    rev: 0acad54c0243c0bb302e757b962918a73ebe79f4
    hooks:
    -   id: black
        language_version: python3
        args: ['--target-version=py35']
-   repo: https://github.com/asottile/reorder_python_imports
    rev: df5d5d28abcf8705bd0c2a622480f6099ca56add
    hooks:
    -   id: reorder-python-imports
        language_version: python3
-   repo: https://github.com/pycqa/flake8
    rev: 121ea4f056fabc82d870cf5deaaf37f035be6d10
    hooks:
    -   id: flake8
        language_version: python3
        args: ['--config=setup.cfg']
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.4.4
    hooks:
    -   id: autopep8
        args: ['--global-config=setup.cfg','--in-place']
-   repo: https://github.com/asottile/pyupgrade
    rev: 9c2e5b08c585f5605f2c2f7e9ce583a236670146
    hooks:
    -   id: pyupgrade
        language_version: python3
-   repo: meta
    hooks:
    -   id: check-hooks-apply
    -   id: check-useless-excludes
