version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.8"
  jobs:
    pre_build:
      - git clone pyessv-archive ~/.esdoc/pyessv-archive

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

formats: all
