# Config file for automatic testing at travis-ci.org
language: python

sudo: false

dist: xenial

matrix:
    fast_finish: true
    include:
      - env: TOXENV=py35
        python: 3.5
      - env: TOXENV=py36
        python: 3.6
      - env: TOXENV=py37
        python: 3.7
      - env: TOXENV=py38-dev
        python: 3.8-dev
      - env: TOXENV=black
        python: 3.7
      - env: TOXENV=docs
        python: 3.5
      - env: TOXENV=pypy
        python: "pypy3"
    allow_failures:
      - env: TOXENV=pypy3
      - env: TOXENV=py38-dev

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
    - sudo -H pip install --upgrade pip
    - pip install -U tox-travis

# command to run tests, e.g. python setup.py tests
script: tox -e $TOXENV

before_deploy:
    - echo "$TRAVIS_TAG" "$TRAVIS_COMMIT"

deploy:
  skip_cleanup: true
  skip_existing: true
  provider: pypi
  distributions: sdist bdist_wheel
  user: 'Zeitsperre'
  password:
    secure: 'Encrypted password'
  on:
    tags: true
    all_branches: true
    condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+[\.]?[a-c-]?[0-9]?[\w-]+\w+
    repo: Zeitsperre/miranda
    python: 3.7
