name: miranda
channels:
  - conda-forge
  - defaults
dependencies:
  - bumpversion
  - cftime
  - coverage
  - custom-inherit >=2.3.0
  - dask
  - distributed
  - fabric
  - fiona
  - flake8
  - geojson
  - geopandas
  - h5netcdf
  - netCDF4
  - numpy
  - pandas
  - paramiko >=2.6.0
  - pint
  - pip
  - pre-commit
  - pyproj
  - pytest
  - python >=3.7
  - rasterio
  - requests
  - rioxarray
  - schema
  - scp
  - shapely
  - tox
  - xarray
  - xclim
