name: miranda

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint_and_docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tox-env:
          - black
          - docs
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - name: Install tox
        run: pip install tox
      - name: Run lint and docs testing suite
        run: tox -e ${{ matrix.tox-env }}

  test:
    needs: lint_and_docs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - tox-env: py37
            python-version: "3.7"
          - tox-env: py38
            python-version: "3.8"
          - tox-env: py39-full
            python-version: "3.9"
          - tox-env: py310
            python-version: "3.10-dev"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python3.10 (deadsnakes version)
      if: "endsWith(matrix.python-version, '-dev')"
      uses: deadsnakes/action@v2.1.1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up Python ${{ matrix.python-version }}
      if: "!endsWith(matrix.python-version, '-dev')"
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install tox
      run: pip install tox
    - name: Test with tox
      run: tox -e ${{ matrix.tox-env }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: report coverage
      uses: AndreMiras/coveralls-python-action@develop
      with:
        flag-name: run-${{ matrix.tox-env }}
        parallel: true

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: AndreMiras/coveralls-python-action@develop
        with:
          parallel-finished: true
